version: '3'
services:
  recipe_book_back_end:
    container_name: recipe_book_back_end
    build: ./recipe-book/server
    image: recipe_book_back_end:latest
    command: node socket.js
    ports:
      - "3000:3000"

  recipe_book_front_end:
    container_name: recipe_book_front_end
    build: ./recipe-book
    image: recipe_book_front_end:latest
    depends_on:
      - recipe_book_back_end
    # links:
    #   - recipe_book_back_end
    ports:
      - "4200:4200"
    networks:
      - recipe-book-internalnet

  cypress_e2e:
    container_name: cypress_e2e
    build: . 
    image: cypress_e2e:latest
    depends_on:
      - recipe_book_back_end
      - recipe_book_front_end
    command: ./start_cypress_e2e.sh
    ports:
      - "5050:5050"
    volumes:
      - './cypress-ci-cd/volumes/master:/app/cypress/results'
      - './start_cypress_e2e.sh:/start_cypress_e2e.sh'

networks:
  recipe-book-internalnet:
    driver: bridge